#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

#apt-get -y install \
#  wget \
#  fonts-liberation \
#  xdg-utils
apt-get -qqy install \
  wget

#wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp
curl --silent -o "/tmp/google-chrome-stable_current_amd64.deb" -L "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
dpkg --install /tmp/google-chrome-stable_current_amd64.deb
apt-get -qqy install --fix-broken                                       
