#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

###
# ubuntu maintained...
apt-get -qqy install docker.io

#
# ...or...
#
# (not sure why tbh)

###
# docker maintained...
#apt-get -q install -y apt-transport-https
#
#curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
#
#add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
#apt-get -q update
#apt-get -q install -y docker-ce

###
# either way,
# still need to solve how to add `docker` to the default groups for an os-login user
# pam_group to the rescue...
echo '*;*;*;Al0000-2400;docker' >> /etc/security/group.conf
echo "auth       optional   pam_group.so" >> /etc/pam.d/chrome-remote-desktop
