#!/bin/bash
#
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export DEBIAN_FRONTEND=noninteractive

#wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb -P /tmp
curl --silent -o "/tmp/chrome-remote-desktop_current_amd64.deb" -L "https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb"
dpkg --install /tmp/chrome-remote-desktop_current_amd64.deb
apt-get -qqy install --fix-broken                                       
# this installs "xbase-clients xvfb" after an "xfce4 desktop-base" install
# this installs "x11-apps x11-session-utils xbase-clients xbitmaps xinit xvfb" after a "cinnamon-desktop-environment" install
# this installs "python3-psutil x11-apps x11-session-utils xbase-clients xbitmaps xinit xvfb" after a "kde-plasma-desktop" install
# this installs "python3-psutil xbase-clients xvfb" after a full-on "kubuntu-desktop" install

default_gnome() {
  echo "exec /etc/X11/Xsession /usr/bin/gnome-session" > /etc/chrome-remote-desktop-session
}

default_xfce4() {
  echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session
}

default_cinnamon() {
  echo "exec /etc/X11/Xsession /usr/bin/cinnamon-session-cinnamon2d" > /etc/chrome-remote-desktop-session
}

default_plasma() {
  echo "exec /etc/X11/Xsession /usr/bin/plasma_session" > /etc/chrome-remote-desktop-session
}

case "$DESKTOP" in
  "kubuntu") default_plasma
    ;;
  "plasma") default_plasma
    ;;
  "cinnamon") default_cinnamon
    ;;
  "xfce4") default_xfce4
    ;;
  "gnome") default_gnome
    ;;
  *) echo "no desktop specified"
    ;;
esac
