#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

apt-get -qq autoremove -y
apt-get -qq clean

rm -rf /var/lib/apt/lists/*

#"rm -f /etc/sudoers.d/90-cloud-init-users",
#"/usr/bin/gpasswd -d packer ubuntu",
#"/usr/bin/touch /var/mail/ubuntu",
#"/usr/sbin/userdel -r -f ubuntu"
